### ISSUE TITLE
Add README note about nginx

### ISSUE THREAD

**Issue by cancan101** [jamesdempsey/docker-mirthconnect#4]
Why is nginx being used?

**Comment by fancyremarker** [comment]
Hey @cancan101! Great question. AFAIK, Mirth Connect itself doesn't natively handle either of the following:
- port redirection via reverse proxies (i.e., URL rewriting)
- `X-Forwarded-Proto`

I added an NGiNX layer in front of Mirth as a shim to achieve both these pieces of functionality. This makes the image play nicer in a Docker environment where containers are meant to be composable, and may be exposed on arbitrary ports. Specifically, this allows us to (e.g.):
- Choose our own protocols/ciphers for terminating SSL, using a separate NGiNX, Apache or other web server.
- Run the Mirth Connect container on an arbitrary external port, and still work (so long as it is ultimately exposed by a load balancer listening on 80/443.

I'll also open a PR explaining this, as you suggested. Also, if Mirth can be configured to handle port redirection or `X-Forwarded-Proto`, please let me know. I couldn't find a way to do either reliably.

**Comment by cancan101** [comment]
What do you mean by port redirection? 

There is this: http://www.mirthcorp.com/community/wiki/display/mirth/Server+Configuration

**Comment by fancyremarker** [comment]
Although Mirth Connect can be configured to listen on arbitrary ports, the following problem still exists: Say I configure Mirth to listen on 8080/8443... Then unless I:
- expose the internal ports on the exact same external ports (i.e., `docker run -p 8080:8080 -p 8443:8443`), and
- expose all reverse proxies (e.g., NGiNX, HAProxy, ELB) on the same external ports

Mirth will not route requests properly (i.e., it will rewrite every URL to reference port 8080/8443 even if the request was made to a downstream proxy listening on a different port).

These two constraints make running the container infeasible in an auto-coordinated Docker environment. At the same time, I agree that this is a superset of the minimal Mirth Connect functionality. So perhaps we could toggle the inclusion of the NGiNX reverse proxy via ENV variable? I could submit that as a PR.
