### ISSUE TITLE
Unexplained Dependencies

### ISSUE THREAD

**Issue by cancan101** [jamesdempsey/docker-mirthconnect#6]
Why are these installed: `tasksel`, `lamp-server^`? 

Why not install just mysql or even postgres (http://www.mirthcorp.com/community/wiki/display/mirth/System+Requirements)?

**Comment by cancan101** [comment]
It looks like the Dockerfile is based on https://gist.github.com/jgautsch/9157402 though that GIST installs both LAMP and then talks about using Postgres.

**Comment by cancan101** [comment]
At the very least, if you are going to use mysql you need to set  /usr/local/mirthconnect/conf/mirth.properties

**Comment by molsches** [comment]
No need for tasksel or lamp-server anymore really. You could just install `apache2`. I forked jgautch's reqs and came up with my own more streamlined version here:  https://gist.github.com/molsches/322bce27f21b65768f12

**Comment by cancan101** [comment]
@molsches Why install apache?

This is what I stripped the Dockerfile down to:
https://github.com/cancan101/docker-mirthconnect/blob/remove_cruft/Dockerfile

**Comment by molsches** [comment]
Ah, I see, you are using nginx for reverse proxy stuff. Nevermind!

**Comment by cancan101** [comment]
Which raises the question: https://github.com/jamesdempsey/docker-mirthconnect/issues/4 is nginx necessary?

**Comment by molsches** [comment]
I use it to manage basic auth and to terminate ssl instead of paying for the Mirth extension that does that.
